### ISSUE TITLE
Error downloading program: private methdo `split' called for nil:NilClass

### ISSUE THREAD

**Issue by alexchamberlain** [robwatkins/4od-dl#2]
Whilst trying to download a different program, I get this error:

```
$ ruby-1.8 4od-dl.rb -p 3416639
D, [2012-10-06T14:20:41.237297 #5015] DEBUG -- : looking for rtmpdump
D, [2012-10-06T14:20:41.242039 #5015] DEBUG -- : looking for ffmpeg
D, [2012-10-06T14:20:41.246553 #5015] DEBUG -- : looking for AtomicParsley
E, [2012-10-06T14:20:41.936409 #5015] ERROR -- : Error downloading program: private method `split' called for nil:NilClass
E, [2012-10-06T14:20:41.936760 #5015] ERROR -- : 4od-dl.rb:59:in `download_4od'
4od-dl.rb:240
4od-dl.rb:231:in `each'
4od-dl.rb:231
```

Any ideas?

The ```streamUri``` is ```http://ll.abrstream.channel4.com/CH4_08_02_24_52341002001002_002_16x9_1500000_.f4m```. This seems to be different to what was expected by the script.

**Comment by dvdsmpsn** [comment]
Please add a comment at the top of the README.md to say that it's currently dead. That'll stop others trying this ;)

**Comment by robwatkins** [comment]
Good idea - have done so!
